-- Seed default NestFlow modular template packs and tasks.
-- Idempotent and safe to re-run.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO template_packs (id, name, is_base_template)
VALUES
  (gen_random_uuid(), 'Prospect', TRUE),
  (gen_random_uuid(), 'Buyer – Under Contract', FALSE),
  (gen_random_uuid(), 'Coming Soon', FALSE),
  (gen_random_uuid(), 'Just Listed', FALSE),
  (gen_random_uuid(), 'Buyer – Post Closing', FALSE),
  (gen_random_uuid(), 'Seller – Under Contract', FALSE),
  (gen_random_uuid(), 'Seller – Post Closing', FALSE)
ON CONFLICT (name) DO UPDATE
SET is_base_template = EXCLUDED.is_base_template,
    updated_at = NOW();

WITH seed_tasks(pack_name, task_name, position) AS (
  VALUES
  ('Prospect', 'Follow up', 1),

  ('Buyer – Under Contract', 'Send [BUC] 1 – The Next Steps email', 1),
  ('Buyer – Under Contract', 'Create group text', 2),
  ('Buyer – Under Contract', 'Add buyer agent contact info to phone', 3),
  ('Buyer – Under Contract', 'Send welcome / celebration cookie', 4),
  ('Buyer – Under Contract', 'Schedule inspections', 5),
  ('Buyer – Under Contract', 'Add inspections to calendar', 6),
  ('Buyer – Under Contract', 'Send [BUC] 2 – Insurance referral email', 7),
  ('Buyer – Under Contract', 'Add lender to contacts and send docs', 8),
  ('Buyer – Under Contract', 'Add title company to contacts and send file', 9),
  ('Buyer – Under Contract', 'Send AboutU questionnaire', 10),
  ('Buyer – Under Contract', 'Send [BUC] 3 – After inspection email', 11),
  ('Buyer – Under Contract', 'Locate and send HOA docs (if needed)', 12),
  ('Buyer – Under Contract', 'Upload inspection reports', 13),
  ('Buyer – Under Contract', 'Add transaction to spreadsheet', 14),
  ('Buyer – Under Contract', 'Confirm appraisal ordered', 15),
  ('Buyer – Under Contract', 'Review appraisal results', 16),
  ('Buyer – Under Contract', 'Negotiate inspection repairs', 17),
  ('Buyer – Under Contract', 'Send [BUC] 4 – RealTracs credit', 18),
  ('Buyer – Under Contract', 'Send [BUC] 5 – Moving links', 19),
  ('Buyer – Under Contract', 'Send [BUC] 6 – Setting up closing', 20),
  ('Buyer – Under Contract', 'Review lingering due diligence items', 21),
  ('Buyer – Under Contract', 'Order home warranty (if needed)', 22),
  ('Buyer – Under Contract', 'Send contract changes to title/lender', 23),
  ('Buyer – Under Contract', 'Schedule final walk-through and closing', 24),
  ('Buyer – Under Contract', 'Coordinate keys', 25),
  ('Buyer – Under Contract', 'Collect repair receipts', 26),
  ('Buyer – Under Contract', 'Submit inspection proposal', 27),
  ('Buyer – Under Contract', 'Confirm CD sent', 28),
  ('Buyer – Under Contract', 'Complete closing day tasks', 29),
  ('Buyer – Under Contract', 'Start post-closing checklist', 30),

  ('Coming Soon', 'Send listing paperwork with special stipulations', 1),
  ('Coming Soon', 'Order professional photos', 2),
  ('Coming Soon', 'Add photo shoot to calendar', 3),
  ('Coming Soon', 'Prefill RealTracs listing', 4),
  ('Coming Soon', 'Post to agent groups / Breakfast Club', 5),
  ('Coming Soon', 'Install Coming Soon sign', 6),
  ('Coming Soon', 'Install lockbox and record serial number', 7),
  ('Coming Soon', 'Create Meta ad', 8),
  ('Coming Soon', 'Adjust Follow Up Boss action plan', 9),
  ('Coming Soon', 'Edit photos', 10),
  ('Coming Soon', 'Switch to Just Listed template', 11),
  ('Coming Soon', 'Write listing description', 12),
  ('Coming Soon', 'MLS Proof to seller', 13),

  ('Just Listed', 'Confirm showing notifications', 1),
  ('Just Listed', 'Launch Meta ad', 2),
  ('Just Listed', 'Confirm lockbox installed', 3),
  ('Just Listed', 'Confirm sign installed', 4),
  ('Just Listed', 'Change rider to FOR SALE', 5),
  ('Just Listed', 'Update SentriSmart address', 6),
  ('Just Listed', 'Fill in IMPORTANT dates', 7),
  ('Just Listed', 'Send thank-you note', 8),
  ('Just Listed', 'Upload affiliate disclosures to MLS', 9),
  ('Just Listed', 'Upload HOA docs to MLS', 10),
  ('Just Listed', 'Link virtual tour in RealTracs', 11),
  ('Just Listed', 'Review additional marketing', 12),
  ('Just Listed', 'Set neighborhood alerts', 13),
  ('Just Listed', 'Seller check-in', 14),
  ('Just Listed', 'Update showing instructions', 15),
  ('Just Listed', 'Send weekly web hits', 16),
  ('Just Listed', 'Evaluate withdraw/cancel', 17),

  ('Buyer – Post Closing', 'Confirm keys received', 1),
  ('Buyer – Post Closing', 'Order closing gift', 2),
  ('Buyer – Post Closing', 'Update Follow Up Boss contact', 3),
  ('Buyer – Post Closing', 'Add to mailing list', 4),
  ('Buyer – Post Closing', 'Confirm Closed in RealTracs', 5),
  ('Buyer – Post Closing', 'Deposit commission check', 6),
  ('Buyer – Post Closing', 'Upload ALTA', 7),
  ('Buyer – Post Closing', 'Confirm sale recorded in Zillow', 8),
  ('Buyer – Post Closing', 'Transfer funds', 9),
  ('Buyer – Post Closing', 'Connect on social media', 10),
  ('Buyer – Post Closing', 'Send closing postcard', 11),
  ('Buyer – Post Closing', 'Request Google review', 12),
  ('Buyer – Post Closing', 'Social proof post', 13),
  ('Buyer – Post Closing', 'Complete referral follow-up', 14),
  ('Buyer – Post Closing', 'Send neighborhood postcard', 15),
  ('Buyer – Post Closing', 'File Sold photo', 16),
  ('Buyer – Post Closing', '1-week check-in', 17),
  ('Buyer – Post Closing', '1-month check-in', 18),
  ('Buyer – Post Closing', '1-year follow-up', 19),
  ('Buyer – Post Closing', '2-year follow-up', 20),
  ('Buyer – Post Closing', '3-year follow-up', 21),
  ('Buyer – Post Closing', '4-year follow-up', 22),
  ('Buyer – Post Closing', '5-year follow-up', 23),

  ('Seller – Under Contract', 'Send executed contract to seller', 1),
  ('Seller – Under Contract', 'Send contract to title company', 2),
  ('Seller – Under Contract', 'Send Next Steps email', 3),
  ('Seller – Under Contract', 'Connect with buyer lender', 4),
  ('Seller – Under Contract', 'Send inspection scheduled email', 5),
  ('Seller – Under Contract', 'Send title insurance discount email', 6),
  ('Seller – Under Contract', 'Confirm earnest money received', 7),
  ('Seller – Under Contract', 'Send moving checklist', 8),
  ('Seller – Under Contract', 'Confirm appraisal ordered', 9),
  ('Seller – Under Contract', 'Confirm appraisal received', 10),
  ('Seller – Under Contract', 'Mark listing Pending in MLS', 11),
  ('Seller – Under Contract', 'Send revisions to title/lender', 12),
  ('Seller – Under Contract', 'Schedule closing and walk-through', 13),
  ('Seller – Under Contract', 'Collect repair receipts', 14),
  ('Seller – Under Contract', 'Remind seller to cancel utilities', 15),
  ('Seller – Under Contract', 'Submit repair proposal', 16),
  ('Seller – Under Contract', 'Confirm CD sent', 17),
  ('Seller – Under Contract', 'Complete closing day tasks', 18),
  ('Seller – Under Contract', 'Begin post-closing checklist', 19),

  ('Seller – Post Closing', 'Pick up sign', 1),
  ('Seller – Post Closing', 'Pick up lockbox', 2),
  ('Seller – Post Closing', 'Mark Closed in RealTracs', 3),
  ('Seller – Post Closing', 'Collect check / ALTA', 4),
  ('Seller – Post Closing', 'Remove SentriSmart assignment', 5),
  ('Seller – Post Closing', 'Order closing gift', 6),
  ('Seller – Post Closing', 'Send closing postcard', 7),
  ('Seller – Post Closing', 'Connect on Facebook', 8),
  ('Seller – Post Closing', 'Update Follow Up Boss profile', 9),
  ('Seller – Post Closing', 'Update mailing address', 10),
  ('Seller – Post Closing', 'Create Just Sold Canva ad', 11),
  ('Seller – Post Closing', 'Post Just Sold on social', 12),
  ('Seller – Post Closing', 'Confirm proceeds received', 13),
  ('Seller – Post Closing', 'Add image to Sold folder', 14),
  ('Seller – Post Closing', 'Request Zillow / Google review', 15),
  ('Seller – Post Closing', 'Complete referral follow-up', 16),
  ('Seller – Post Closing', 'Deposit commission check', 17),
  ('Seller – Post Closing', 'Transfer funds', 18)
)
INSERT INTO template_tasks (id, pack_id, name, position)
SELECT
  gen_random_uuid(),
  p.id,
  st.task_name,
  st.position
FROM seed_tasks st
JOIN template_packs p ON p.name = st.pack_name
ON CONFLICT (pack_id, name) DO UPDATE
SET position = EXCLUDED.position,
    updated_at = NOW();
